//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMascotas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mascotas
    {
        public int Id { get; set; }
        public string animal { get; set; }
        public string raza { get; set; }
        public string ubicacion { get; set; }
        public Nullable<bool> sexo { get; set; }
        public string descripcion { get; set; }
        public string vacunas { get; set; }
        public Nullable<int> edad { get; set; }
        public Nullable<bool> perdidoadopcion { get; set; }
        public Nullable<bool> encontradoadoptado { get; set; }
    }
}
