//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMascotas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mascotas
    {
        public int ID { get; set; }
        public string Animal { get; set; }
        public string Raza { get; set; }
        public string Ubicacion { get; set; }
        public Nullable<bool> Sexo { get; set; }
        public string Descripcion { get; set; }
        public string Vacunas { get; set; }
        public Nullable<int> Edad { get; set; }
        public int Status { get; set; }
    }
}
