//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMascotas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int Id { get; set; }
        public string empresa { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string usuario1 { get; set; }
        public string pass { get; set; }
        public string localidad { get; set; }
        public Nullable<System.DateTime> fechadenacimiento { get; set; }
        public string dni { get; set; }
        public string tipodeusuario { get; set; }
    }
}
