//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMascotas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int ID { get; set; }
        public string Empresa { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Nombre_de_Usuario { get; set; }
        public string Pass { get; set; }
        public string Localidad { get; set; }
        public Nullable<System.DateTime> Fecha_de_nacimiento { get; set; }
        public string DNI { get; set; }
        public string Tipo_de_usuario { get; set; }
        public string Email { get; set; }
    }
}
