//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMascotas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int ID { get; set; }
        public string Empresa { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Nombre_de_Usuario { get; set; }
        public string Pass { get; set; }
        public string Localidad { get; set; }
        public Nullable<System.DateTime> Fecha_de_nacimiento { get; set; }
        public string DNI { get; set; }
        public string Tipo_de_usuario { get; set; }
    }
}
